# Generated by Django 4.2.16 on 2024-11-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_pedidoporproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.produtos')),
            ],
        ),
    ]
