# Generated by Django 4.2.16 on 2024-11-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_temporary_password',
            field=models.BooleanField(default=True),
        ),
    ]
